# Generated by Django 6.1.1 on 2026-09-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Максим Кузнецов', max_length=255)),
                ('role', models.CharField(default='Старший менеджер по продажам', max_length=255)),
                ('department', models.CharField(default='Департамент корпоративных продаж', max_length=255)),
                ('email', models.EmailField(blank=True, default='m.kuznetsov@company.kz', max_length=254)),
                ('phone', models.CharField(blank=True, default='+7 (701) 987-65-43', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80')),
                ('monthly_target', models.DecimalField(decimal_places=2, default=7500000.0, max_digits=12)),
                ('current_sales', models.DecimalField(decimal_places=2, default=7800000.0, max_digits=12)),
                ('deals_count', models.IntegerField(default=28)),
                ('rank_in_team', models.IntegerField(default=1)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=34.5, max_digits=5)),
                ('whatsapp_daily_digest', models.BooleanField(default=True)),
                ('whatsapp_stalled_deals', models.BooleanField(default=True)),
                ('whatsapp_critical_kpi', models.BooleanField(default=True)),
                ('ai_response_mode', models.CharField(choices=[('detailed', 'Подробный с аналитикой и инсайтами'), ('concise', 'Лаконичный (Bullet points)'), ('finance', 'Финансовый (Только цифры и таблицы)')], default='detailed', max_length=32)),
                ('ai_auto_suggest_next_actions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
