# Generated by Django 6.1.1 on 2026-09-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('client_type', models.CharField(choices=[('private', 'Частный девелопер'), ('state', 'Государственный заказчик'), ('quasi_state', 'Квазигосударственный сектор'), ('contractor', 'Генподрядчик / Монтажники'), ('designer', 'Проектная организация'), ('other', 'Прочее')], default='private', max_length=32)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('chat_id', models.CharField(blank=True, default='', max_length=128)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=64)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('qdrant_point_id', models.CharField(blank=True, default='', max_length=64)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сырое сообщение',
                'verbose_name_plural': 'Сырые сообщения',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_sales',
            field=models.DecimalField(decimal_places=2, default=31790000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deals_count',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='Отдел продаж Aqua Kip', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='kamil@aquakip.kz', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Камиль', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=50000000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='+7 (701) 123-45-67', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Ведущий менеджер по продажам', max_length=255),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('private', 'Частный'), ('state', 'Государственный'), ('quasi_state', 'Квазигосударственный')], default='private', max_length=32)),
                ('status', models.CharField(choices=[('lead', 'Лид / Первичный контакт'), ('qualification', 'Квалификация / Сбор ТЗ'), ('design', 'Проектирование / Экспертиза'), ('proposal_sent', 'КП отправлено'), ('contract_signing', 'Согласование / Договор'), ('in_execution', 'В исполнении / Производство / Монтаж'), ('completed', 'Завершен / Сдан'), ('stalled', 'Завис / Требует внимания'), ('lost', 'Проигран / Архив')], default='qualification', max_length=64)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('target_margin_percent', models.DecimalField(decimal_places=2, default=16.8, max_digits=5)),
                ('actual_margin_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('equipment_type', models.CharField(blank=True, default='БТП', max_length=128)),
                ('priority', models.CharField(choices=[('A+++', 'A+++ Стратегический'), ('A++', 'A++ Высокий'), ('A+', 'A+ Приоритетный'), ('standard', 'Стандартный')], default='standard', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Проект / Объект',
                'verbose_name_plural': 'Проекты / Объекты',
                'ordering': ['-contract_amount'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('advance', 'Аванс'), ('milestone', 'Промежуточный платёж'), ('final', 'Окончательный расчет'), ('debt_collection', 'Взыскание задолженности')], default='milestone', max_length=32)),
                ('status', models.CharField(choices=[('expected', 'Ожидается к сбору'), ('received', 'Получено на расчетный счет'), ('delayed', 'Задержка платежа')], default='received', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='api.project')),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('info', 'Инфо'), ('warning', 'Внимание'), ('critical', 'Критично')], default='info', max_length=16)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.userprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.project')),
            ],
            options={
                'verbose_name': 'Бизнес-событие',
                'verbose_name_plural': 'Бизнес-события',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_person', models.CharField(blank=True, default='', max_length=255)),
                ('commitment_text', models.TextField()),
                ('promised_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'В работе'), ('fulfilled', 'Выполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='pending', max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Критический'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=16)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='api.userprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='api.project')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='api.rawmessage')),
            ],
            options={
                'verbose_name': 'Обязательство / Обещание',
                'verbose_name_plural': 'Обязательства / Обещания',
                'ordering': ['deadline', 'id'],
            },
        ),
    ]
