# Generated by Django 6.1.1 on 2026-09-25 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_rawmessage_alter_userprofile_conversion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная конфигурация OpenRouter', max_length=128, verbose_name='Конфигурация')),
                ('embedding_provider_url', models.CharField(default='https://openrouter.ai/api/v1', max_length=255, verbose_name='Embeddings Base URL')),
                ('embedding_model_name', models.CharField(default='liquid/lfm-2.5-embedding-350m:free', max_length=128, verbose_name='Embeddings Model')),
                ('embedding_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Embeddings API Key')),
                ('embedding_dimension', models.IntegerField(default=1024, verbose_name='Размерность вектора')),
                ('chat_provider_url', models.CharField(default='https://openrouter.ai/api/v1', max_length=255, verbose_name='Chat Base URL')),
                ('chat_model_name', models.CharField(default='nvidia/nemotron-3-ultra-550b-a55b:free', max_length=128, verbose_name='Chat LLM Model')),
                ('chat_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Chat API Key')),
                ('chat_temperature', models.FloatField(default=0.2, verbose_name='Temperature')),
                ('system_prompt_worker', models.TextField(default='Ты эксперт-аналитик рабочей группы продаж AquaKip.\nТвоя задача — извлечь из сообщения факты по коммерческим сделкам.\nНе выдумывай данные. Если чего-то нет в тексте — возвращай null.\nФормат ответа — строго валидный JSON:\n{\n  "is_deal_fact": true|false,\n  "confidence": 0.0-1.0,\n  "object_name": "Название объекта",\n  "company_name": "Компания заказчика или null",\n  "direction": "Оборудование: БМК, БТП, НС, Котлы и т.д.",\n  "contract_number": "Номер договора или null",\n  "deal_period": "Период сделки или null",\n  "stage": "lead|qualification|proposal_sent|contract_signing|in_execution|completed|stalled",\n  "contract_amount": число или null,\n  "cost_amount": число или null,\n  "paid_amount": число или null,\n  "barter_amount": число или null,\n  "guarantee_amount": число или null,\n  "avr_status": "Закрыт|Не закрыт|null",\n  "responsible_name": "Имя менеджера",\n  "current_action": "Что сделано",\n  "next_action": "Следующий шаг",\n  "next_action_at": "ISO 8601 дата или null",\n  "decision_maker": "ЛПР или null",\n  "blocker": "Блокер или null",\n  "priority": "A+++|A++|A+|standard",\n  "can_create_deal": true|false\n}', verbose_name='Промпт извлечения сделок из чата')),
                ('system_prompt_assistant', models.TextField(default='Ты аналитический ассистент Mazory AI платформы продаж AquaKip.\nОтвечай точно, структурированно, опираясь на факты из базы данных и сообщений.\nИспользуй тенге (₸) для сумм. Если пользователь просит графики или сравнения, возвращай данные в понятной форме.', verbose_name='Промпт чат-ассистента для пользователей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная конфигурация')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки моделей AI',
                'verbose_name_plural': 'Настройки моделей AI',
            },
        ),
        migrations.CreateModel(
            name='BitrixSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AquaKip Bitrix24 Portal', max_length=128, verbose_name='Название интеграции')),
                ('webhook_url', models.CharField(default='https://aquakip.bitrix24.kz/rest/148/71vwif5ivu5f4abk/', max_length=255, verbose_name='REST Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Синхронизация активна')),
                ('auto_create_deals', models.BooleanField(default=True, verbose_name='Авто-создание сделок в Bitrix24')),
                ('deal_category_id', models.IntegerField(default=0, verbose_name='ID воронки сделок')),
                ('default_assigned_by_id', models.IntegerField(default=1, verbose_name='ID ответственного по умолчанию')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_sync_status', models.TextField(blank=True, default='', verbose_name='Статус последней операции')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки Bitrix24',
                'verbose_name_plural': 'Настройки Bitrix24',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='КОМАНДА ПОДДЕРЖКИ ПРОДАЖ', max_length=255, verbose_name='Название чата / группы')),
                ('group_jid', models.CharField(default='120363024823904923@g.us', help_text='Например: 120363024823904923@g.us', max_length=128, verbose_name='WhatsApp Group JID')),
                ('session_name', models.CharField(default='default', max_length=64, verbose_name='Имя сессии в WAHA')),
                ('waha_api_url', models.CharField(default='http://waha:3000', max_length=255, verbose_name='URL WAHA API')),
                ('waha_api_key', models.CharField(blank=True, default='mazory-waha-key-2026', max_length=128, verbose_name='WAHA API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Мониторинг активен')),
                ('status', models.CharField(default='WORKING', max_length=32, verbose_name='Статус подключения')),
                ('last_qr_code', models.TextField(blank=True, default='', verbose_name='QR-код (base64)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка WhatsApp (WAHA)',
                'verbose_name_plural': 'Настройки WhatsApp (WAHA)',
            },
        ),
        migrations.AlterModelOptions(
            name='rawmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Сырое сообщение WhatsApp', 'verbose_name_plural': 'Сырые сообщения WhatsApp'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='company',
            name='bitrix_company_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='avr_status',
            field=models.CharField(default='Не закрыт', max_length=64, verbose_name='Накладные / АВР'),
        ),
        migrations.AddField(
            model_name='project',
            name='barter_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Сумма бартера ₸'),
        ),
        migrations.AddField(
            model_name='project',
            name='bitrix_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Bitrix24 ID сделки'),
        ),
        migrations.AddField(
            model_name='project',
            name='blocker',
            field=models.TextField(blank=True, default='', verbose_name='Блокер / Проблема'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_action',
            field=models.TextField(blank=True, default='', verbose_name='Последнее действие'),
        ),
        migrations.AddField(
            model_name='project',
            name='deal_period',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Период сделки'),
        ),
        migrations.AddField(
            model_name='project',
            name='decision_maker',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ЛПР'),
        ),
        migrations.AddField(
            model_name='project',
            name='guarantee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Гарантийные оплаты ₸'),
        ),
        migrations.AddField(
            model_name='project',
            name='next_action',
            field=models.TextField(blank=True, default='', verbose_name='Следующий шаг'),
        ),
        migrations.AddField(
            model_name='project',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок следующего действия'),
        ),
        migrations.AlterField(
            model_name='businessevent',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='businessevent',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.userprofile', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='businessevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.project', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='businessevent',
            name='severity',
            field=models.CharField(choices=[('info', 'Инфо'), ('warning', 'Внимание'), ('critical', 'Критично')], default='info', max_length=16, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='businessevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='commitment_text',
            field=models.TextField(verbose_name='Суть обещания'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='counterparty_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кому обещано / ЛПР'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='api.userprofile', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='api.project', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='severity',
            field=models.CharField(choices=[('critical', 'Критический'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=16, verbose_name='Срочность'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('pending', 'В работе'), ('fulfilled', 'Выполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма ₸'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий / Основание'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_date',
            field=models.DateField(verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Аванс'), ('milestone', 'Промежуточный платёж'), ('final', 'Окончательный расчет'), ('barter', 'Взаимозачёт / Бартер'), ('debt_collection', 'Взыскание задолженности')], default='milestone', max_length=32, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='api.project', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='status',
            field=models.CharField(choices=[('expected', 'Ожидается к сбору'), ('received', 'Получено на расчетный счет'), ('delayed', 'Задержка платежа')], default='received', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Фактическая маржа %'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Сумма Договора ₸'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Себестоимость ₸'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Остаток / Дебиторка ₸'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_type',
            field=models.CharField(blank=True, default='БТП', max_length=128, verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.userprofile', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Заметки / История'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Оплачено ₸'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('A+++', 'A+++ Стратегический'), ('A++', 'A++ Высокий'), ('A+', 'A+ Приоритетный'), ('standard', 'Стандартный')], default='standard', max_length=16, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('private', 'Частный'), ('state', 'Государственный'), ('quasi_state', 'Квазигосударственный')], default='private', max_length=32, verbose_name='Тип заказчика'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Лид / Первичный контакт'), ('qualification', 'Квалификация / Сбор ТЗ'), ('design', 'Проектирование / Экспертиза'), ('proposal_sent', 'КП отправлено'), ('contract_signing', 'Согласование / Договор'), ('in_execution', 'В исполнении / Производство / Монтаж'), ('completed', 'Завершен / Сдан'), ('stalled', 'Завис / Требует внимания'), ('lost', 'Проигран / Архив')], default='qualification', max_length=64, verbose_name='Статус сделки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_margin_percent',
            field=models.DecimalField(decimal_places=2, default=16.8, max_digits=5, verbose_name='Плановая маржа %'),
        ),
    ]
