# Generated by Django 6.1.1 on 2026-09-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aisettings_bitrixsettings_whatsappconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deal_period',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Период сделки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_type',
            field=models.CharField(blank=True, default='БТП', max_length=255, verbose_name='Оборудование'),
        ),
    ]
