# Generated by Django 6.1.1 on 2026-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixsettings',
            name='auto_create_tasks',
            field=models.BooleanField(default=True, verbose_name='Создавать задачи в Bitrix24 по дедлайнам'),
        ),
        migrations.AddField(
            model_name='bitrixsettings',
            name='auto_import_deals',
            field=models.BooleanField(default=True, verbose_name='Авто-импорт сделок из CRM в Mazory'),
        ),
        migrations.AddField(
            model_name='bitrixsettings',
            name='hourly_sync_enabled',
            field=models.BooleanField(default=True, verbose_name='Ежечасная фоновая синхронизация'),
        ),
        migrations.AddField(
            model_name='bitrixsettings',
            name='last_hourly_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего запуска диспетчера'),
        ),
        migrations.AddField(
            model_name='bitrixsettings',
            name='sync_timeline_comments',
            field=models.BooleanField(default=True, verbose_name='Публиковать саммари в таймлайн сделки'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='bitrix_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID задачи в Bitrix24'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_bitrix_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней синхронизации с Bitrix24'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_chat_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней активности в чате'),
        ),
        migrations.AddField(
            model_name='project',
            name='needs_bitrix_sync',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Требует синхронизации с Bitrix24'),
        ),
        migrations.AddField(
            model_name='project',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Каноническое название для дедупликации'),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('chat', 'WhatsApp Чат'), ('bitrix_crm', 'Bitrix24 CRM'), ('manual', 'Ручной ввод')], default='chat', max_length=32, verbose_name='Источник сделки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Bitrix24 User ID'),
        ),
    ]
