# Generated by Django 6.1.1 on 2026-09-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bitrixsettings_auto_create_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixDealChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_deal_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID сделки в Bitrix24')),
                ('action', models.CharField(choices=[('create', 'Создание сделки (crm.deal.add)'), ('update', 'Обновление сделки (crm.deal.update)')], db_index=True, max_length=32, verbose_name='Действие')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], db_index=True, default='success', max_length=32, verbose_name='Статус')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Отправленные данные (Payload)')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Ответ Bitrix24')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Измененные поля')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Длительность (мс)')),
                ('triggered_by', models.CharField(blank=True, default='system', max_length=128, verbose_name='Инициатор / Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время отправки')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitrix_change_logs', to='api.project', verbose_name='Объект / Сделка')),
            ],
            options={
                'verbose_name': 'Лог изменения сделки Bitrix24',
                'verbose_name_plural': 'Логи изменений сделок Bitrix24',
                'ordering': ['-created_at'],
            },
        ),
    ]
