# Generated by Django 6.1.1 on 2026-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bitrixdealchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixsettings',
            name='inbound_token',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Секретный токен входящего вебхука'),
        ),
    ]
