# Generated by Django 6.1.1 on 2026-09-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_system_prompt_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Фактическая маржа %'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_margin_percent',
            field=models.DecimalField(decimal_places=2, default=16.8, max_digits=8, verbose_name='Плановая маржа %'),
        ),
    ]
