# Generated by Django 6.1.1 on 2026-09-26 13:43

from django.db import migrations, models
from decimal import Decimal


def setup_manager_bitrix_ids_and_projects(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    Project = apps.get_model('api', 'Project')

    # 1. Привязка bitrix_user_id к профилям
    id_mapping = {
        1: '40',   # Камиль (Камилжан Авутов)
        3: '132',  # Самат (Самат Жумагалиев)
        4: '34',   # Улугбек (Улугбек Ергешев)
        5: '146',  # Турар (Турар Тулегенов)
        6: '68',   # Вячеслав (Вячеслав Медведев)
        7: '20',   # Жанат (Жанат Беисбаев)
        8: '4',    # Aqua kip engineering (Руководство / Админ Портала)
    }

    user_by_bx_id = {}
    for uid, bx_id in id_mapping.items():
        user = UserProfile.objects.filter(id=uid).first()
        if user:
            user.bitrix_user_id = bx_id
            user.save(update_fields=['bitrix_user_id'])
            user_by_bx_id[bx_id] = user

    # 2. Подтягивание реальных ответственных из Bitrix24
    try:
        from api.bitrix_service import BitrixService
        deals = BitrixService.fetch_all_paged("crm.deal.list", {"select": ["ID", "ASSIGNED_BY_ID"], "limit": 1000})
        deal_mgr_map = {str(d.get("ID")): str(d.get("ASSIGNED_BY_ID")) for d in deals if d.get("ID")}
        for proj in Project.objects.all():
            if proj.bitrix_id and str(proj.bitrix_id) in deal_mgr_map:
                assigned_bx_id = deal_mgr_map[str(proj.bitrix_id)]
                target_user = user_by_bx_id.get(assigned_bx_id)
                if target_user and proj.manager_id != target_user.id:
                    proj.manager_id = target_user.id
                    proj.save(update_fields=['manager_id'])
    except Exception:
        pass

    # 3. Актуализировать current_sales для каждого менеджера
    from django.db.models import Sum
    for user in UserProfile.objects.all():
        total_paid = Project.objects.filter(manager_id=user.id).aggregate(tot=Sum('paid_amount'))['tot'] or 0
        if total_paid > 0:
            user.current_sales = Decimal(str(total_paid))
            user.save(update_fields=['current_sales'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_system_prompt_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Фактическая маржа %'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_margin_percent',
            field=models.DecimalField(decimal_places=2, default=16.8, max_digits=10, verbose_name='Плановая маржа %'),
        ),
        migrations.RunPython(setup_manager_bitrix_ids_and_projects, migrations.RunPython.noop),
    ]
