# Generated by Django 6.1.1 on 2026-09-27 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_commitment_is_verified_financialrecord_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProcessingTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=128, verbose_name='ID сообщения WhatsApp')),
                ('whatsapp_chat_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Чат / Группа WhatsApp')),
                ('whatsapp_sender_phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон отправителя')),
                ('whatsapp_sender_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя отправителя')),
                ('whatsapp_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время сообщения WhatsApp')),
                ('whatsapp_content', models.TextField(verbose_name='Текст сообщения WhatsApp')),
                ('whatsapp_raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой payload WAHA')),
                ('earlier_messages_context', models.JSONField(blank=True, default=list, verbose_name='Найденные сообщения из истории (Qdrant RAG / Чат)')),
                ('earlier_messages_count', models.IntegerField(default=0, verbose_name='Количество зависимых сообщений')),
                ('bitrix_matched_deal_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID сделки в Bitrix24')),
                ('bitrix_deal_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название сделки в Bitrix24')),
                ('bitrix_deal_stage', models.CharField(blank=True, default='', max_length=64, verbose_name='Стадия в Bitrix24')),
                ('bitrix_deal_opportunity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма сделки в Bitrix24 ₸')),
                ('bitrix_search_query', models.CharField(blank=True, default='', max_length=255, verbose_name='Поисковый запрос в Bitrix24')),
                ('bitrix_company_data', models.JSONField(blank=True, default=dict, verbose_name='Данные компании в Bitrix24')),
                ('bitrix_raw_deal', models.JSONField(blank=True, default=dict, verbose_name='Полные данные сделки из Bitrix24')),
                ('bitrix_known_deals_summary', models.TextField(blank=True, default='', verbose_name='Сводка сделок компании, переданная в AI')),
                ('ai_extracted_facts', models.JSONField(blank=True, default=dict, verbose_name='Извлеченные факты AI')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Уверенность AI (0.0 - 1.0)')),
                ('pipeline_action', models.CharField(choices=[('created_deal', 'Создана новая сделка'), ('updated_deal', 'Обновлена существующая сделка'), ('matched_bitrix_imported', 'Импортирована сделка из Bitrix24'), ('commitment_created', 'Зафиксировано обязательство'), ('financial_record_created', 'Зафиксирована оплата'), ('non_commercial', 'Информационное / Некоммерческое сообщение'), ('error', 'Ошибка обработки')], db_index=True, default='non_commercial', max_length=64, verbose_name='Действие пайплайна')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('warning', 'Требует внимания'), ('error', 'Ошибка')], db_index=True, default='success', max_length=32, verbose_name='Статус обработки')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='Резюме итоговой записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания трассировки')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_traces', to='api.commitment', verbose_name='Созданное обязательство')),
                ('financial_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_traces', to='api.financialrecord', verbose_name='Созданная запись оплаты')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_traces', to='api.project', verbose_name='Объект / Сделка')),
                ('raw_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='api.rawmessage', verbose_name='Сырое сообщение WhatsApp')),
            ],
            options={
                'verbose_name': 'Трассировка пайплайна',
                'verbose_name_plural': 'Трассировки пайплайна',
                'ordering': ['-created_at'],
            },
        ),
    ]
