# Generated by Django 6.1.1 on 2026-09-28 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_messageprocessingtrace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminMFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_secret", models.TextField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_counter", models.BigIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="AsyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(default="chat", max_length=32)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=16),
                ),
                ("request", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("access_fingerprint", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("target_type", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("before_after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_jti_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("device", models.CharField(blank=True, max_length=256)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientProjectAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "invited"),
                            ("active", "active"),
                            ("revoked", "revoked"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fact_type",
                    models.CharField(
                        choices=[
                            ("project", "project"),
                            ("payment", "payment"),
                            ("commitment", "commitment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("proposed_changes", models.JSONField(default=dict)),
                (
                    "base_project_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("superseded", "superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("confidence", models.FloatField(default=0)),
                ("uncertainties", models.JSONField(blank=True, default=list)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("field_name", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=255, unique=True)),
                ("category", models.CharField(default="info", max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(default="whatsapp", max_length=16)),
                ("attempt_no", models.PositiveIntegerField(default=1)),
                ("state", models.CharField(default="queued", max_length=16)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                ("deduplication_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(db_index=True, default="pending", max_length=16),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="KZT", max_length=3)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PrivateAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="private/%Y/%m/")),
                ("content_type", models.CharField(max_length=128)),
                ("sha256", models.CharField(max_length=64)),
                ("published_to_client", models.BooleanField(default=False)),
                ("transcript", models.TextField(blank=True)),
                ("state", models.CharField(default="queued", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("source", models.CharField(default="review", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ReminderOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commitment_version", models.PositiveIntegerField()),
                ("rule_code", models.CharField(max_length=32)),
                ("rule_version", models.PositiveIntegerField(default=1)),
                ("scheduled_at", models.DateTimeField()),
                ("state", models.CharField(default="queued", max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="SalesTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="KZT", max_length=3)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(blank=True, max_length=64)),
                ("to_stage", models.CharField(max_length=64)),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history_complete_from", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Менеджер"),
                            ("team_lead", "Руководитель"),
                            ("finance", "Финансист"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "invited"),
                            ("active", "active"),
                            ("revoked", "revoked"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                ("invited_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="businessevent",
            name="deduplication_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="commitment",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commitment",
            name="deadline_precision",
            field=models.CharField(default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="commitment",
            name="original_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commitment",
            name="postponed_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="commitment",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="credited_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credited_payments",
                to="api.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="currency",
            field=models.CharField(default="KZT", max_length=3),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.financialrecord",
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="source_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="messageprocessingtrace",
            name="attempt_no",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="messageprocessingtrace",
            name="error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="messageprocessingtrace",
            name="model_version",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="messageprocessingtrace",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="currency",
            field=models.CharField(default="KZT", max_length=3),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.whatsappconfig",
            ),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="processing_state",
            field=models.CharField(db_index=True, default="received", max_length=32),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="received_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="sent_at_known",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="session_name",
            field=models.CharField(default="default", max_length=64),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="source",
            field=models.CharField(default="waha", max_length=32),
        ),
        migrations.AddField(
            model_name="rawmessage",
            name="source_revision",
            field=models.CharField(default="0", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notification_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="Asia/Almaty", max_length=64),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="bitrixsettings",
            name="webhook_url",
            field=models.CharField(
                default="", max_length=255, verbose_name="REST Webhook URL"
            ),
        ),
        migrations.AlterField(
            model_name="businessevent",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="api.userprofile",
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="businessevent",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="api.project",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="commitment",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commitments",
                to="api.userprofile",
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="commitment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commitments",
                to="api.project",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="financialrecord",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_records",
                to="api.project",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="rawmessage",
            name="message_id",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="conversion_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_sales",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="deals_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="monthly_target",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="rank_in_team",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappconfig",
            name="group_jid",
            field=models.CharField(
                default="",
                help_text="Например: 120363024823904923@g.us",
                max_length=128,
                verbose_name="WhatsApp Group JID",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappconfig",
            name="waha_api_key",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="WAHA API Key"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawmessage",
            constraint=models.UniqueConstraint(
                fields=("source", "session_name", "message_id", "source_revision"),
                name="message_source_revision_unique",
            ),
        ),
        migrations.AddField(
            model_name="adminmfa",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="asyncoperation",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chataccess",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_grants",
                to="api.whatsappconfig",
            ),
        ),
        migrations.AddField(
            model_name="chataccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_access",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="factcandidate",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="factcandidate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="factcandidate",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="factcandidate",
            name="trace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="api.messageprocessingtrace",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="candidate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_commitment",
                to="api.factcandidate",
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="candidate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_payment",
                to="api.factcandidate",
            ),
        ),
        migrations.AddField(
            model_name="factevidence",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence",
                to="api.factcandidate",
            ),
        ),
        migrations.AddField(
            model_name="factevidence",
            name="raw_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.rawmessage"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="business_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.businessevent",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.commitment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="api.notification",
            ),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="business_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.businessevent",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="financial_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="api.financialrecord",
            ),
        ),
        migrations.AddField(
            model_name="paymentscheduleitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_schedule",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="schedule_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="api.paymentscheduleitem",
            ),
        ),
        migrations.AddField(
            model_name="privateattachment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.project"
            ),
        ),
        migrations.AddField(
            model_name="privateattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="reminderoccurrence",
            name="commitment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.commitment"
            ),
        ),
        migrations.AddField(
            model_name="reminderoccurrence",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.notification",
            ),
        ),
        migrations.AddField(
            model_name="reminderoccurrence",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="salestarget",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salestarget",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targets",
                to="api.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="stagetransition",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_history",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="stagetransition",
            name="project_revision",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="api.projectrevision"
            ),
        ),
        migrations.AddField(
            model_name="factcandidate",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.team"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.team",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.team",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="api.team",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="asyncoperation",
            constraint=models.UniqueConstraint(
                fields=("requested_by", "idempotency_key"),
                name="operation_request_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="chataccess",
            constraint=models.UniqueConstraint(
                fields=("user", "config"), name="chat_access_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientprojectaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="client_project_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel", "attempt_no"),
                name="delivery_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentscheduleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="schedule_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="allocation_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                fields=("financial_record", "schedule_item"), name="allocation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrevision",
            constraint=models.UniqueConstraint(
                fields=("project", "version"), name="project_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderoccurrence",
            constraint=models.UniqueConstraint(
                fields=(
                    "commitment",
                    "commitment_version",
                    "rule_code",
                    "rule_version",
                    "recipient",
                    "scheduled_at",
                ),
                name="reminder_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.UniqueConstraint(
                fields=("profile", "month", "version"), name="target_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("profile", "month"),
                name="target_active_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="target_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("user", "team", "role"), name="membership_unique"
            ),
        ),
    ]
