# Generated by Django 6.1.1 on 2026-09-28 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_platform_access_facts_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmessage",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Плановая маржа %",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("archived", False),
                    ("team__isnull", False),
                    models.Q(("normalized_name", ""), _negated=True),
                ),
                fields=("team", "normalized_name"),
                name="project_team_identity_unique",
            ),
        ),
    ]
