# Generated by Django 6.1.1 on 2026-09-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_legacy_quarantine"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentallocation",
            name="allocation_positive",
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="allocation_nonzero",
            ),
        ),
    ]
