# Generated by Django 6.1.1 on 2026-09-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_reversal_allocations"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmessage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="actual_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                verbose_name="Фактическая маржа %",
            ),
        ),
    ]
