# Generated by Django 6.1.1 on 2026-09-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_attachment_provenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitment",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Подтверждено ли обязательство. Непроверенные задачи не учитываются в SLA и просрочках.",
                verbose_name="Проверено",
            ),
        ),
        migrations.AlterField(
            model_name="financialrecord",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Подтвержден ли факт оплаты. Непроверенные оплаты не учитываются в сборе денег и выполнении планов.",
                verbose_name="Проверено",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Подтверждена ли достоверность данных сделки. Непроверенные сделки исключаются из аналитики и синхронизации с CRM.",
                verbose_name="Проверено",
            ),
        ),
    ]
