# Generated by Django 6.1.1 on 2026-09-28 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_explicit_approval_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=32)),
                ("model_name", models.CharField(max_length=128)),
                ("duration_ms", models.PositiveIntegerField()),
                ("succeeded", models.BooleanField()),
                ("input_tokens", models.PositiveIntegerField(null=True)),
                ("output_tokens", models.PositiveIntegerField(null=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=8, max_digits=14, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="salestarget",
            name="target_version_unique",
        ),
        migrations.RemoveConstraint(
            model_name="salestarget",
            name="target_active_unique",
        ),
        migrations.AddField(
            model_name="salestarget",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="low_margin_percent",
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name="team",
            name="rules_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="team",
            name="stalled_days",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.UniqueConstraint(
                fields=("team", "profile", "month", "currency", "version"),
                name="target_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("team", "profile", "month", "currency"),
                name="target_active_unique",
            ),
        ),
    ]
