# Generated by Django 6.1.1 on 2026-09-28 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_analytics_scope_and_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerusage',
            name='outbox_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_usage', to='api.outboxevent'),
        ),
    ]
