# Generated by Django 6.1.1 on 2026-09-28 10:47

from django.db import migrations, models


def verify_attempt_identity(apps, schema_editor):
    Trace = apps.get_model("api", "MessageProcessingTrace")
    duplicate = (
        Trace.objects.using(schema_editor.connection.alias)
        .filter(raw_message__isnull=False)
        .values("raw_message_id", "attempt_no")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .exists()
    )
    if duplicate:
        raise RuntimeError(
            "Historical duplicate attempt numbers require review; no audit records were changed."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_provider_usage_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="context_safety_tokens",
            field=models.PositiveIntegerField(
                default=2048, verbose_name="Технический запас, токены"
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="context_window_tokens",
            field=models.PositiveIntegerField(
                default=256000, verbose_name="Окно контекста, токены"
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="max_completion_tokens",
            field=models.PositiveIntegerField(
                default=8192, verbose_name="Резерв ответа, токены"
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="tokenizer_id",
            field=models.CharField(
                default="nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
                max_length=255,
                verbose_name="Токенизатор",
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="tokenizer_revision",
            field=models.CharField(
                default="77df655d5e9f8362164ed14dd8b48f8bce657498",
                max_length=64,
                verbose_name="Версия токенизатора",
            ),
        ),
        migrations.AddField(
            model_name="messageprocessingtrace",
            name="context_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Полнота и бюджет контекста"
            ),
        ),
        migrations.AddField(
            model_name="messageprocessingtrace",
            name="operation_key",
            field=models.CharField(
                blank=True, editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="rawmessage",
            index=models.Index(
                fields=["config", "timestamp", "id"], name="raw_chat_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawmessage",
            index=models.Index(
                fields=["team", "source", "project", "timestamp", "id"],
                name="raw_project_time_idx",
            ),
        ),
        migrations.RunPython(verify_attempt_identity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="messageprocessingtrace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("raw_message__isnull", False)),
                fields=("raw_message", "attempt_no"),
                name="trace_source_attempt_unique",
            ),
        ),
    ]
