# Generated by Django 6.1.1 on 2026-09-29 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_message_context_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="daily_budget_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0 — бюджет из настроек сервера.",
                max_digits=12,
                verbose_name="Бюджет AI в сутки, USD",
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="daily_request_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 — лимит из настроек сервера. Учитываются чат и embeddings.",
                verbose_name="Лимит запросов AI в сутки",
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="message_processing_paused",
            field=models.BooleanField(
                default=False,
                help_text="Новые задания ждут в очереди. Уже отправленные запросы завершаются.",
                verbose_name="Приостановить анализ и индексацию сообщений",
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppHistoryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Задание включено"),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 — только вручную. Период больше 0 включает автоматические запуски.",
                        verbose_name="Период запуска, минуты",
                    ),
                ),
                (
                    "analyze_after_import",
                    models.BooleanField(
                        default=True, verbose_name="Анализировать после импорта"
                    ),
                ),
                (
                    "page_size",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="Размер одного запроса (1–1000), не ограничение всей истории.",
                        verbose_name="Сообщений в одной странице WAHA",
                    ),
                ),
                (
                    "initial_wait_seconds",
                    models.PositiveIntegerField(
                        default=180,
                        verbose_name="Ожидание начальной синхронизации, секунды",
                    ),
                ),
                (
                    "poll_seconds",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Интервал проверки, секунды"
                    ),
                ),
                (
                    "stable_scans_required",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Количество одинаковых полных проходов перед импортом (2–10).",
                        verbose_name="Стабильных проходов истории",
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Следующий автоматический запуск",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history_job",
                        to="api.whatsappconfig",
                        verbose_name="Группа WhatsApp",
                    ),
                ),
            ],
            options={
                "verbose_name": "настройка импорта WhatsApp",
                "verbose_name_plural": "Настройки импорта WhatsApp",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppHistoryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting_connection", "Ожидает WhatsApp"),
                            ("waiting_sync", "Ожидает синхронизацию истории"),
                            ("collecting", "Собирает историю"),
                            ("importing", "Сохраняет сообщения"),
                            ("analyzing", "Анализирует сообщения"),
                            ("paused", "Приостановлено"),
                            ("completed", "Завершено"),
                            ("completed_with_errors", "Завершено с ошибками анализа"),
                            ("empty", "WAHA не вернул сообщений"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        db_index=True,
                        default="waiting_connection",
                        max_length=32,
                        verbose_name="Состояние",
                    ),
                ),
                ("resume_state", models.CharField(blank=True, max_length=32)),
                (
                    "source_snapshot",
                    models.JSONField(
                        default=dict, verbose_name="Источник на момент запуска"
                    ),
                ),
                (
                    "settings_snapshot",
                    models.JSONField(
                        default=dict, verbose_name="Параметры на момент запуска"
                    ),
                ),
                ("step", models.PositiveIntegerField(default=0)),
                ("offset", models.PositiveIntegerField(default=0)),
                ("scan_number", models.PositiveIntegerField(default=1)),
                ("stable_scans", models.PositiveIntegerField(default=0)),
                ("last_digest", models.CharField(blank=True, max_length=64)),
                (
                    "cutoff_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="История по момент времени"
                    ),
                ),
                ("stage_ready_at", models.DateTimeField(blank=True, null=True)),
                ("last_page_signature", models.CharField(blank=True, max_length=64)),
                (
                    "fetched_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Получено из WAHA"
                    ),
                ),
                (
                    "imported_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Новых сообщений"
                    ),
                ),
                (
                    "existing_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Уже были в базе"
                    ),
                ),
                (
                    "no_text_count",
                    models.PositiveIntegerField(default=0, verbose_name="Без текста"),
                ),
                (
                    "scheduled_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Направлено на анализ"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ошибки"
                    ),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, verbose_name="Подробности"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="api.whatsapphistoryjob",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="history_import_runs",
                        to="api.rawmessage",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запустил",
                    ),
                ),
            ],
            options={
                "verbose_name": "запуск импорта WhatsApp",
                "verbose_name_plural": "Запуски импорта WhatsApp",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppHistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("seen_scan", models.PositiveIntegerField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.whatsapphistoryrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="whatsapphistoryrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "waiting_connection",
                            "waiting_sync",
                            "collecting",
                            "importing",
                            "analyzing",
                            "paused",
                        ),
                    )
                ),
                fields=("job",),
                name="one_active_whatsapp_import",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapphistoryitem",
            index=models.Index(
                fields=["run", "timestamp", "id"], name="history_item_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsapphistoryitem",
            constraint=models.UniqueConstraint(
                fields=("run", "message_id"), name="history_run_message_unique"
            ),
        ),
    ]
