# Generated by Django 6.1.1 on 2026-09-29 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_aisettings_daily_budget_usd_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="whatsapphistoryrun",
            name="one_active_whatsapp_import",
        ),
        migrations.AddField(
            model_name="whatsapphistoryjob",
            name="checkpoint_source",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="whatsapphistoryjob",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Последняя успешная проверка",
            ),
        ),
        migrations.AddField(
            model_name="whatsapphistoryjob",
            name="new_message_poll_seconds",
            field=models.PositiveIntegerField(
                default=5,
                help_text="5–3600 секунд. Работает постоянно, пока задание включено; период в минутах не используется.",
                verbose_name="Интервал проверки новых сообщений, секунды",
            ),
        ),
        migrations.AddField(
            model_name="whatsapphistoryjob",
            name="new_messages_since",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Проверено по"
            ),
        ),
        migrations.AddField(
            model_name="whatsapphistoryjob",
            name="new_messages_started_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Начальная точка новых сообщений",
            ),
        ),
        migrations.AddField(
            model_name="whatsapphistoryjob",
            name="only_new",
            field=models.BooleanField(
                default=False,
                help_text="Постоянно получать новые сообщения с сохранённой точки. Старую историю можно загрузить полным импортом.",
                verbose_name="Только новые",
            ),
        ),
        migrations.AddField(
            model_name="whatsapphistoryrun",
            name="incremental_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="whatsapphistoryjob",
            name="interval_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Для полного импорта: 0 — только вручную, больше 0 — автоматические запуски. В режиме «Только новые» используется интервал в секундах.",
                verbose_name="Период запуска, минуты",
            ),
        ),
        migrations.AlterField(
            model_name="whatsapphistoryrun",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting_connection", "Ожидает WhatsApp"),
                    ("waiting_sync", "Ожидает синхронизацию истории"),
                    ("watching", "Ожидаем новые сообщения"),
                    ("collecting", "Собирает историю"),
                    ("importing", "Сохраняет сообщения"),
                    ("analyzing", "Анализирует сообщения"),
                    ("paused", "Приостановлено"),
                    ("completed", "Завершено"),
                    ("completed_with_errors", "Завершено с ошибками анализа"),
                    ("empty", "WAHA не вернул сообщений"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменено"),
                ],
                db_index=True,
                default="waiting_connection",
                max_length=32,
                verbose_name="Состояние",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsapphistoryrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "waiting_connection",
                            "waiting_sync",
                            "watching",
                            "collecting",
                            "importing",
                            "analyzing",
                            "paused",
                        ),
                    )
                ),
                fields=("job",),
                name="one_active_whatsapp_import",
            ),
        ),
    ]
