# Generated by Django 6.1.1 on 2026-09-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_whatsapphistoryrun_one_active_whatsapp_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='chat_api_format',
            field=models.CharField(choices=[('openai_compatible', 'OpenAI-compatible'), ('anthropic_messages', 'Anthropic Messages')], default='openai_compatible', help_text='OpenAI-compatible использует Chat Base URL ниже; Anthropic Messages использует ANTHROPIC_BASE_URL из окружения сервера.', max_length=32, verbose_name='Формат Chat API'),
        ),
        migrations.AddField(
            model_name='providerusage',
            name='api_format',
            field=models.CharField(choices=[('openai_compatible', 'OpenAI-compatible'), ('anthropic_messages', 'Anthropic Messages')], default='openai_compatible', max_length=32),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='daily_request_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 — лимит из настроек сервера. Учитываются все внешние AI-запросы: embeddings, chat и подсчёт токенов.', verbose_name='Лимит запросов AI в сутки'),
        ),
    ]
