# Generated by Django 6.1.1 on 2026-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_crm_candidate_matching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='chat_api_format',
            field=models.CharField(choices=[('openai_compatible', 'OpenAI-compatible'), ('anthropic_messages', 'Anthropic Messages')], default='openai_compatible', help_text='Определяет протокол запросов к редактируемому Chat Base URL.', max_length=32, verbose_name='Формат Chat API'),
        ),
    ]
