# Generated by Django 6.1.1 on 2026-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_aisettings_chat_api_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='daily_budget_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 — без ограничений.', max_digits=12, verbose_name='Бюджет AI в сутки, USD'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='daily_request_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 — без ограничений. Учитываются все внешние AI-запросы: embeddings, chat и подсчёт токенов.', verbose_name='Лимит запросов AI в сутки'),
        ),
    ]
