# Generated by Django 6.1.1 on 2026-10-02 08:36

import django.db.models.deletion
from django.db import migrations, models


def assign_teams(apps, schema_editor):
    Commitment = apps.get_model("api", "Commitment")
    for item in Commitment.objects.select_related(
        "project", "candidate", "source_message__config"
    ).iterator():
        item.team_id = (
            (item.project.team_id if item.project_id else None)
            or (item.candidate.team_id if item.candidate_id else None)
            or (
                item.source_message.config.team_id
                if item.source_message_id and item.source_message.config_id
                else None
            )
            or (item.source_message.team_id if item.source_message_id else None)
        )
        item.save(update_fields=["team"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_aisettings_daily_budget_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="responsible_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Исполнитель по переписке",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commitments",
                to="api.team",
            ),
        ),
        migrations.RunPython(assign_teams, migrations.RunPython.noop),
    ]
