# Generated by Django 6.1.1 on 2026-10-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_contextual_commitments"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmCatalogSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generation", models.PositiveIntegerField(default=0)),
                ("state", models.CharField(default="idle", max_length=16)),
                ("cursor", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="api.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DialogueThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(db_index=True, max_length=64)),
                ("identity", models.CharField(max_length=64, unique=True)),
                ("topic", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("ready", "ready"),
                            ("unknown", "unknown"),
                            ("superseded", "superseded"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("snapshot_max_id", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.whatsappconfig",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="api.dialoguethread",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("state", models.CharField(max_length=16)),
                ("message_snapshot", models.JSONField(default=list)),
                ("extraction", models.JSONField(default=list)),
                ("completion_reason", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="api.dialoguethread",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="factcandidate",
            name="thread_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="api.threadrevision",
            ),
        ),
        migrations.CreateModel(
            name="ThreadMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thought_state",
                    models.CharField(
                        choices=[
                            ("intermediate", "intermediate"),
                            ("final", "final"),
                            ("unknown", "unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("discusses", "discusses"),
                            ("answers", "answers"),
                            ("clarifies", "clarifies"),
                            ("cancels", "cancels"),
                            ("fulfills", "fulfills"),
                        ],
                        default="discusses",
                        max_length=16,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=1000)),
                (
                    "raw_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="api.rawmessage",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_links",
                        to="api.dialoguethread",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("thread", "raw_message"), name="thread_message_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="threadrevision",
            constraint=models.UniqueConstraint(
                fields=("thread", "version"), name="thread_revision_unique"
            ),
        ),
    ]
