# Generated by Django 6.1.1 on 2026-10-04 09:14

from django.db import migrations, models


def confirm_existing_identities(apps, schema_editor):
    Project = apps.get_model("api", "Project")
    Project.objects.filter(
        models.Q(is_verified=True)
        | models.Q(source="bitrix_crm", bitrix_id__isnull=False)
    ).update(identity_confirmed=True)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_crmcatalogsync_dialoguethread_threadrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="identity_confirmed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(confirm_existing_identities, migrations.RunPython.noop),
    ]
