# Generated by Django 6.1.1 on 2026-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_project_identity_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadrevision",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="threadrevision",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
