# Generated by Django 6.1.1 on 2026-10-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_mcptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_context_messages',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_crm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_input_tokens',
            field=models.PositiveIntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_policy_version',
            field=models.CharField(default='whatsapp-autonomous-v1', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.team'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='amount_precision',
            field=models.CharField(default='exact', max_length=16),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='direction',
            field=models.CharField(default='income', max_length=16),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='event_kind',
            field=models.CharField(default='payment', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentscheduleitem',
            name='amount_precision',
            field=models.CharField(default='exact', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentscheduleitem',
            name='direction',
            field=models.CharField(default='income', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentscheduleitem',
            name='state',
            field=models.CharField(default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentscheduleitem',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='whatsapp_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ExternalObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_key', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=32)),
                ('local_type', models.CharField(max_length=32)),
                ('local_id', models.PositiveBigIntegerField()),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('origin_key', models.CharField(max_length=255, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='FactDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('accepted', 'accepted'), ('deferred', 'deferred'), ('rejected', 'rejected'), ('superseded', 'superseded')], max_length=16)),
                ('actor_kind', models.CharField(default='system', max_length=16)),
                ('policy_version', models.CharField(max_length=64)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('reason_code', models.CharField(max_length=64)),
                ('explanation', models.TextField()),
                ('validation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='api.factcandidate')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.factdecision')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='api.company')),
                ('decision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.factdecision')),
            ],
        ),
        migrations.CreateModel(
            name='FactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.factdecision')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fact_events', to='api.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team')),
            ],
            options={
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='CrmDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_version', models.PositiveIntegerField()),
                ('state', models.CharField(default='pending', max_length=32)),
                ('patch', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.outboxevent')),
                ('external_object_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.externalobjectlink')),
                ('fact_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.factevent')),
            ],
        ),
        migrations.AddField(
            model_name='paymentscheduleitem',
            name='fact_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.factevent'),
        ),
        migrations.CreateModel(
            name='FieldAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('value_state', models.CharField(default='known', max_length=16)),
                ('value', models.JSONField(null=True)),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.commitment')),
                ('fact_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.factevent')),
                ('financial_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.financialrecord')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assertions', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='MessageArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(default='unavailable', max_length=32)),
                ('extracted_text', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('raw_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='api.rawmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='commitment',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.participant'),
        ),
        migrations.CreateModel(
            name='ParticipantIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('resolution_state', models.CharField(default='resolved', max_length=16)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('decision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.factdecision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.factdecision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scope', models.CharField(max_length=64)),
                ('complete_through', models.DateTimeField(blank=True, null=True)),
                ('gaps', models.JSONField(default=list)),
                ('counts', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='SourceWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_version', models.CharField(max_length=64)),
                ('state', models.CharField(db_index=True, default='pending', max_length=32)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='api.rawmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='externalobjectlink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('team', 'integration_key', 'object_type', 'external_id'), name='external_object_namespace_unique'),
        ),
        migrations.AddConstraint(
            model_name='factdecision',
            constraint=models.UniqueConstraint(fields=('candidate', 'policy_version', 'input_fingerprint'), name='fact_decision_input_unique'),
        ),
        migrations.AddConstraint(
            model_name='companyalias',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_name'), name='company_alias_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commitment__isnull', True), ('financial_record__isnull', True), ('project__isnull', False)), models.Q(('commitment__isnull', False), ('financial_record__isnull', True), ('project__isnull', True)), models.Q(('commitment__isnull', True), ('financial_record__isnull', False), ('project__isnull', True)), _connector='OR'), name='assertion_one_target'),
        ),
        migrations.AddConstraint(
            model_name='participantidentity',
            constraint=models.UniqueConstraint(fields=('namespace', 'value'), name='participant_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectalias',
            constraint=models.UniqueConstraint(fields=('project', 'normalized_name'), name='project_alias_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectparty',
            constraint=models.UniqueConstraint(fields=('project', 'company', 'role'), name='project_party_unique'),
        ),
        migrations.AddConstraint(
            model_name='sourcecheckpoint',
            constraint=models.UniqueConstraint(fields=('team', 'source_scope'), name='source_checkpoint_unique'),
        ),
        migrations.AddConstraint(
            model_name='sourceworkitem',
            constraint=models.UniqueConstraint(fields=('raw_message', 'processing_version'), name='source_work_version_unique'),
        ),
    ]
