# Generated by Django 6.1.1 on 2026-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_aisettings_autonomous_context_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_reconcile_cursor',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
