# Generated by Django 6.1.1 on 2026-10-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_aisettings_autonomous_reconcile_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_daily_token_limit',
            field=models.PositiveBigIntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='autonomous_max_in_flight',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='ProviderReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=32)),
                ('reserved_tokens', models.PositiveBigIntegerField()),
                ('state', models.CharField(default='reserved', max_length=16)),
                ('lease_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.aisettings')),
                ('usage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.providerusage')),
            ],
        ),
    ]
