# Generated by Django 6.1.1 on 2026-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_autonomous_legacy_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerreservation',
            name='purpose',
            field=models.CharField(default='live', max_length=16),
        ),
    ]
