# Generated by Django 6.1.1 on 2026-10-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_providerreservation_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageartifact',
            name='raw_message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='api.rawmessage'),
        ),
    ]
