# Generated by Django 6.1.1 on 2026-10-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_messageartifact_raw_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisettings',
            name='message_processing_paused',
        ),
    ]
