# Generated by Django 6.1.1 on 2026-10-06 20:59

import django.db.models.deletion
import hashlib
import json
from django.db import migrations, models


def backfill_analysis_sources(apps, schema_editor):
    Event = apps.get_model('api', 'OutboxEvent')
    Raw = apps.get_model('api', 'RawMessage')
    batch = []
    for event in Event.objects.filter(event_type='extract_message', state__in=['pending','enqueued','processing']).iterator(chunk_size=250):
        raw_id = event.payload.get('raw_id')
        if type(raw_id) is not int:
            continue
        raw = Raw.objects.select_related('config').filter(pk=raw_id).first()
        if not raw:
            continue
        team = raw.config.team_id if raw.config_id else raw.team_id
        if not team or (not raw.config_id and not raw.project_id):
            continue
        event.analysis_source_key = hashlib.sha256(json.dumps([team, raw.config_id, raw.source, raw.session_name, raw.chat_id, raw.project_id if not raw.config_id else None]).encode()).hexdigest()
        event.analysis_position = raw.id
        batch.append(event)
        if len(batch) == 250:
            Event.objects.bulk_update(batch,['analysis_source_key','analysis_position']);batch=[]
    if batch:
        Event.objects.bulk_update(batch,['analysis_source_key','analysis_position'])
    Settings = apps.get_model('api','AISettings')
    for cfg in Settings.objects.all():
        cfg.analysis_output_token_limit = min(4096,cfg.max_completion_tokens)
        cfg.analysis_input_token_limit = max(1,min(16384,cfg.context_window_tokens-cfg.analysis_output_token_limit-cfg.context_safety_tokens))
        cfg.save(update_fields=['analysis_input_token_limit','analysis_output_token_limit'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_aisettings_message_processing_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAnalysisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, default='queued', max_length=16)),
                ('disposition', models.CharField(blank=True, max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'результат анализа сообщения',
                'verbose_name_plural': 'Результаты анализа сообщений',
            },
        ),
        migrations.AddField(
            model_name='aisettings',
            name='analysis_input_token_limit',
            field=models.PositiveIntegerField(default=16384, verbose_name='Вход анализа, токены'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='analysis_output_token_limit',
            field=models.PositiveIntegerField(default=4096, verbose_name='Ответ анализа, токены'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='analysis_target_message_limit',
            field=models.PositiveIntegerField(default=8, verbose_name='Сообщений в пакете анализа'),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='analysis_position',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='analysis_source_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['analysis_source_key', 'state', 'next_attempt_at', 'analysis_position'], name='analysis_dispatch_idx'),
        ),
        migrations.AddField(
            model_name='historyanalysisitem',
            name='outbox_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.outboxevent'),
        ),
        migrations.AddField(
            model_name='historyanalysisitem',
            name='raw_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rawmessage'),
        ),
        migrations.AddField(
            model_name='historyanalysisitem',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_items', to='api.whatsapphistoryrun'),
        ),
        migrations.AddField(
            model_name='historyanalysisitem',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.messageprocessingtrace'),
        ),
        migrations.AddConstraint(
            model_name='historyanalysisitem',
            constraint=models.UniqueConstraint(fields=('run', 'raw_message'), name='history_analysis_coverage_unique'),
        ),
        migrations.RunPython(backfill_analysis_sources, migrations.RunPython.noop),
    ]
