# Generated by Django 6.1.1 on 2026-10-07 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_runs(apps, schema_editor):
    Run=apps.get_model('api','WhatsAppHistoryRun')
    Run.objects.filter(settings_snapshot__only_new=True).update(run_kind='monitor')


def backfill_aliases(apps, schema_editor):
    Raw=apps.get_model('api','RawMessage')
    Alias=apps.get_model('api','WhatsAppMessageAlias')
    batch=[]
    for raw in Raw.objects.filter(source='waha',config__isnull=False).iterator(chunk_size=250):
        batch.append(Alias(config_id=raw.config_id,raw_message_id=raw.id,session_name=raw.session_name,chat_id=raw.chat_id,namespace='waha',external_id=raw.message_id,source_revision=raw.source_revision))
        if len(batch)==250:
            Alias.objects.bulk_create(batch,ignore_conflicts=True);batch=[]
    if batch:Alias.objects.bulk_create(batch,ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_history_analysis_source_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppExportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('line_start', models.PositiveIntegerField()),
                ('line_end', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField()),
                ('time_precision', models.CharField(max_length=8)),
                ('kind', models.CharField(max_length=16)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('resolution_state', models.CharField(max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'запись TXT-экспорта',
                'verbose_name_plural': 'Записи TXT-экспорта и причины',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppExportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whatsapp_exports/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=64)),
                ('timezone', models.CharField(max_length=64)),
                ('date_order', models.CharField(default='DMY', max_length=3)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('diagnostics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'экспорт WhatsApp',
                'verbose_name_plural': 'Экспорты WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=64)),
                ('chat_id', models.CharField(max_length=128)),
                ('namespace', models.CharField(max_length=16)),
                ('external_id', models.CharField(max_length=128)),
                ('source_revision', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='whatsapphistoryrun',
            name='one_active_whatsapp_import',
        ),
        migrations.AddField(
            model_name='factcandidate',
            name='materialization_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='factevent',
            name='is_superseded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='whatsapphistoryrun',
            name='import_kind',
            field=models.CharField(choices=[('waha', 'WhatsApp (WAHA)'), ('file', 'TXT-экспорт'), ('saved', 'Сохранённая история')], default='waha', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsapphistoryrun',
            name='run_kind',
            field=models.CharField(choices=[('full', 'Полный проход'), ('monitor', 'Монитор новых сообщений')], default='full', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsappexportentry',
            name='raw_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.rawmessage'),
        ),
        migrations.AddField(
            model_name='whatsappexportupload',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='api.whatsapphistoryjob'),
        ),
        migrations.AddField(
            model_name='whatsappexportupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappexportentry',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='api.whatsappexportupload'),
        ),
        migrations.AddField(
            model_name='whatsapphistoryrun',
            name='export_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='api.whatsappexportupload'),
        ),
        migrations.RunPython(backfill_runs,migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='whatsapphistoryrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('waiting_connection', 'waiting_sync', 'watching', 'collecting', 'importing', 'analyzing', 'paused'))), fields=('job', 'run_kind'), name='one_active_whatsapp_run_kind'),
        ),
        migrations.AddField(
            model_name='whatsappmessagealias',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.whatsappconfig'),
        ),
        migrations.AddField(
            model_name='whatsappmessagealias',
            name='raw_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_aliases', to='api.rawmessage'),
        ),
        migrations.AddConstraint(
            model_name='whatsappexportupload',
            constraint=models.UniqueConstraint(fields=('job', 'source_key', 'sha256', 'timezone', 'date_order'), name='whatsapp_export_upload_unique'),
        ),
        migrations.AddConstraint(
            model_name='whatsappexportentry',
            constraint=models.UniqueConstraint(fields=('upload', 'ordinal'), name='whatsapp_export_entry_unique'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessagealias',
            constraint=models.UniqueConstraint(fields=('config', 'session_name', 'chat_id', 'namespace', 'external_id', 'source_revision'), name='whatsapp_transport_alias_unique'),
        ),
        migrations.RunPython(backfill_aliases,migrations.RunPython.noop),
    ]
