# Generated by Django 6.1.1 on 2026-10-07 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_whatsapp_export_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptoken',
            name='purpose',
            field=models.CharField(choices=[('external', 'External'), ('portal', 'Portal')], default='external', max_length=16),
        ),
        migrations.AddField(
            model_name='mcptoken',
            name='token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='mcptoken',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('purpose', 'portal')), fields=('user',), name='one_active_portal_mcp_token'),
        ),
    ]
