# Generated by Django 6.1.1 on 2026-10-07 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_portal_mcp_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmProjectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_stage_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "external_stage_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_manager_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "external_manager_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "opportunity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="KZT", max_length=3)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_snapshot",
                        to="api.project",
                    ),
                ),
            ],
        ),
    ]
