# Generated by Django 6.1.1 on 2026-10-07 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_crmprojectsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый диалог', max_length=200)),
                ('default_scope', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('user_text', models.TextField()),
                ('answer_document', models.JSONField(default=dict)),
                ('resolved_intent', models.JSONField(default=dict)),
                ('effective_scope', models.JSONField(default=dict)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='api.analyticsconversation')),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_turn', to='api.asyncoperation')),
                ('parent_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.analyticsturn')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_plan', models.JSONField(default=dict)),
                ('presentation', models.JSONField(default=dict)),
                ('coverage', models.JSONField(default=dict)),
                ('access_fingerprint', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('parent_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.analyticsartifact')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.analyticsturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='analyticsturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='analytics_turn_sequence_unique'),
        ),
    ]
