# Generated by Django 6.1.1 on 2026-10-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_analyticsconversation_analyticsturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='analysis_input_token_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 — всё доступное окно модели за вычетом ответа и технического запаса. Положительное число — отдельный пользовательский предел.', verbose_name='Вход анализа, токены'),
        ),
    ]
