# Generated by Django 6.1.1 on 2026-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_aisettings_analysis_input_token_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
