# Generated by Django 6.1.1 on 2026-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_temporal_sql_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsconversation',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
