# Generated by Django 6.1.1 on 2026-10-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_dialogue_activity'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='WhatsAppHistoryRunMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rawmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rawmessage')),
                ('whatsapphistoryrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.whatsapphistoryrun')),
            ],
            options={
                'db_table': 'api_whatsapphistoryrun_messages',
                'default_permissions': ('view',),
                'unique_together': {('whatsapphistoryrun', 'rawmessage')},
            },
        ),
        migrations.AlterField(
            model_name='whatsapphistoryrun',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='history_import_runs', through='api.WhatsAppHistoryRunMessage', to='api.rawmessage'),
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        state_operations=state_operations,
        database_operations=[migrations.RunSQL(
            sql="""ALTER TABLE public.api_whatsapphistoryrun_messages ADD COLUMN created_at timestamptz NULL, ADD COLUMN updated_at timestamptz NULL;
            CREATE TRIGGER mazory_record_times BEFORE INSERT OR UPDATE ON public.api_whatsapphistoryrun_messages FOR EACH ROW EXECUTE FUNCTION public.mazory_record_times();""",
            reverse_sql="""DROP TRIGGER mazory_record_times ON public.api_whatsapphistoryrun_messages;
            ALTER TABLE public.api_whatsapphistoryrun_messages DROP COLUMN created_at, DROP COLUMN updated_at;""",
        )],
    )]
