[project]
name = "mazory-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "django-q2>=1.11.1",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg[binary]>=3.2.0",
    "qdrant-client>=1.13.0",
    "numpy>=1.26.0",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "django-unfold>=0.108.0",
]
