import { describe, it, expect, vi } from 'vitest'
import { validatePresentation } from '../../types/presentation'
import { chartOptions } from '../options'
import { mount } from '@vue/test-utils'
import KpiDashboardView from '../../components/KpiDashboardView.vue'
vi.mock('../../composables/api', () => ({ api: vi.fn().mockResolvedValue({ teams: [], profiles: [], projects: [] }) }))
vi.stubGlobal('matchMedia', () => ({ matches: true }))
function fixture() { return { version: '1.0', title: 'Answer', summary: '', blocks: [{ id: 'test', kind: 'bar', dataset_id: 'ds', encoding: { category: 'name', value: 'amount' }, size: 'wide' }], datasets: { ds: { dataset_id: 'ds', columns: [{ name: 'name', type: 'text', unit: null }, { name: 'amount', type: 'money', unit: 'KZT' }], rows: [{ name: '<img src=x onerror=alert(1)>', amount: '123.45' }], normalized_query: { currency: 'KZT' }, timezone: 'Asia/Almaty', coverage: { status: 'partial', message: 'Partial' }, returned_count: 1, total_groups: 1, truncated: false, definition: 'Verified', evidence: [] } } } }
describe('untrusted presentation boundary', () => {
  it('preserves exact financial strings and accepts null', () => { const input=fixture(); const result=validatePresentation(input); expect(result.datasets.ds.rows[0].amount).toBe('123.45') })
  it.each(['unknown-kind', 'missing-column', 'number-money', 'foreign-dataset', 'duplicate-id', 'options-code', 'infinite-number'])('rejects %s before mounting', scenario => { const input=fixture(); const changed: Record<string, unknown> = input.blocks[0]; if (scenario==='unknown-kind') changed.kind='eval'; if (scenario==='missing-column') changed.encoding={ category:'name', value:'foreign' }; if (scenario==='number-money') (input.datasets.ds.rows[0] as Record<string, unknown>).amount=123; if (scenario==='foreign-dataset') changed.dataset_id='foreign'; if (scenario==='duplicate-id') input.blocks.push(input.blocks[0]); if (scenario==='options-code') changed.options={ formatter:'eval' }; if (scenario==='infinite-number') (input.datasets.ds.rows[0] as Record<string, unknown>).amount=Infinity; expect(() => validatePresentation(input)).toThrow() })
  it('does not silently cut thirteen bars', () => { const input=fixture(); input.datasets.ds.rows=Array.from({length:13}, (_,i)=>({name:`Category ${i}`,amount:'0.00'})); input.datasets.ds.returned_count=13;input.datasets.ds.total_groups=13;const result=validatePresentation(input); const option=chartOptions(result.blocks[0], result.datasets.ds); const series=option.series as {data: unknown[]}[]; expect(series[0].data).toHaveLength(13); expect(option.tooltip).toMatchObject({ renderMode:'richText' }) })
  it('text answer suppresses previously loaded KPI', () => { const wrapper=mount(KpiDashboardView,{ props: { data: {} as never, widget:null, responseText:'New answer', presentation:null, hasChatResponse:true, isLoading:false, period:'this_month' }, global:{ stubs:{ PresentationRenderer:true } } }); expect(wrapper.text()).toContain('New answer');expect(wrapper.text()).not.toContain('Прогноз поступлений');wrapper.unmount() })
})
